//! Golden parity tests against the reference pyte 0.8.2 emulator.
//!
//! `tests/golden.json` is generated by `tests/gen_golden.py` (feeding pyte the
//! same inputs) and committed, so this test needs no Python at CI time. For
//! every case we replay the identical byte stream through the Rust port and
//! assert the display, cursor, title, icon name, captured device reports, and
//! the full styled buffer match pyte exactly. The disassembler cases check
//! `dis()` output against pyte's `DebugScreen`.

use base64::Engine;
use serde_json::{json, Value};

use stryke_terminal::screens::Screen;
use stryke_terminal::streams::Stream;

const GOLDEN: &str = include_str!("golden.json");

fn decode(b64: &str) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(b64)
        .expect("valid base64 in golden fixture")
}

/// Build the observable state of a screen as a JSON object comparable to the
/// golden fixture (order-independent for the styled buffer cells).
fn observe(screen: &Screen) -> Value {
    let mut buffer = Vec::with_capacity(screen.lines as usize);
    for y in 0..screen.lines {
        let mut row = Vec::with_capacity(screen.columns as usize);
        for x in 0..screen.columns {
            row.push(serde_json::to_value(screen.cell(x, y)).unwrap());
        }
        buffer.push(Value::Array(row));
    }
    json!({
        "display": screen.display(),
        "cursor": {
            "x": screen.cursor.x,
            "y": screen.cursor.y,
            "hidden": screen.cursor.hidden,
        },
        "title": screen.title,
        "icon_name": screen.icon_name,
        "outgoing": screen.outgoing,
        "buffer": buffer,
    })
}

#[test]
fn golden_screen_cases() {
    let golden: Value = serde_json::from_str(GOLDEN).unwrap();
    let cases = golden["cases"].as_object().unwrap();

    let mut checked = 0;
    for (name, case) in cases {
        let cols = case["cols"].as_i64().unwrap();
        let lines = case["lines"].as_i64().unwrap();
        let kind = case["kind"].as_str().unwrap();

        let mut screen = if kind == "history" {
            let history = case["history"].as_u64().unwrap() as usize;
            let ratio = case["ratio"].as_f64().unwrap();
            Screen::with_history(cols, lines, history, ratio)
        } else {
            Screen::new(cols, lines)
        };
        let mut stream = Stream::new_bytes();

        for chunk in case["feeds"].as_array().unwrap() {
            let bytes = decode(chunk.as_str().unwrap());
            stream.feed_bytes(&mut screen, &bytes);
        }
        for op in case["pages"].as_array().unwrap() {
            let op = op.as_str().unwrap().to_string();
            match op.as_str() {
                "prev_page" => screen.event("prev_page", |s| s.prev_page()),
                "next_page" => screen.event("next_page", |s| s.next_page()),
                other => panic!("unknown page op {other} in case {name}"),
            }
        }

        let actual = observe(&screen);
        let expected = json!({
            "display": case["display"],
            "cursor": case["cursor"],
            "title": case["title"],
            "icon_name": case["icon_name"],
            "outgoing": case["outgoing"],
            "buffer": case["buffer"],
        });

        assert_eq!(actual, expected, "golden mismatch in case '{name}'");
        checked += 1;
    }
    assert!(
        checked >= 40,
        "expected the full golden battery, ran {checked}"
    );
}

#[test]
fn golden_disassembler_cases() {
    let golden: Value = serde_json::from_str(GOLDEN).unwrap();
    let dis = golden["dis"].as_object().unwrap();

    // Reproduce the FFI `terminal__dis` recorder inline so the test exercises
    // the same Stream path the export uses.
    struct Recorder {
        events: Vec<Value>,
    }
    impl stryke_terminal::streams::Listener for Recorder {
        fn draw(&mut self, data: &str) {
            self.events.push(json!(["draw", [data], {}]));
        }
        fn dispatch(&mut self, name: &str, args: &[i64], private: bool) {
            let kwargs = if private {
                json!({ "private": true })
            } else {
                json!({})
            };
            self.events.push(json!([name, args, kwargs]));
        }
        fn define_charset(&mut self, code: char, mode: char) {
            self.events
                .push(json!(["define_charset", [code.to_string()], { "mode": mode.to_string() }]));
        }
        fn set_icon_name(&mut self, name: &str) {
            self.events.push(json!(["set_icon_name", [name], {}]));
        }
        fn set_title(&mut self, title: &str) {
            self.events.push(json!(["set_title", [title], {}]));
        }
    }

    for (name, expected) in dis {
        // The golden input is not stored separately; reconstruct it from the
        // known dis fixtures by name.
        let input: &[u8] = match name.as_str() {
            "dis_bell" => b"\x07",
            "dis_sgr" => b"\x1b[20m",
            "dis_cup" => b"\x1b[3;4H",
            "dis_mixed" => b"\x1b[Jfoo",
            "dis_private" => b"\x1b[?7h",
            "dis_title" => b"\x1b]2;hi\x07",
            other => panic!("unknown dis case {other}"),
        };
        let mut stream = Stream::new_bytes();
        let mut rec = Recorder { events: Vec::new() };
        stream.feed_bytes(&mut rec, input);
        assert_eq!(
            Value::Array(rec.events),
            *expected,
            "dis mismatch in case '{name}'"
        );
    }
}
